### ISSUE TITLE
Appears to break when permalink: false is set in markdown frontmatter

### ISSUE THREAD

**Issue by jamieomaguire** [kentaroi/eleventy-plugin-clean#3]
Thanks for making this plugin!

I've noticed in my project that if I set `permalink: false` in any markdown file's front matter, the plugin breaks with the following error message:

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing template: "false" (via EleventyTemplateError)
[11ty] 2. Transform `eleventy-plugin-clean` encountered an error when transforming ./src/topics/topic-1.md. (via EleventyTransformError)
[11ty] 3. The "path" argument must be of type string. Received type boolean (false) (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (false)
[11ty]     at new NodeError (node:internal/errors:387:5)
[11ty]     at validateString (node:internal/validators:162:11)
[11ty]     at Object.normalize (node:path:1128:5)
[11ty]     at updateFileRecord (/project/node_modules/eleventy-plugin-clean/lib/eleventy-clean.js:86:18)
[11ty]     at Object.<anonymous> (/project/node_modules/eleventy-plugin-clean/lib/eleventy-clean.js:154:5)
[11ty]     at Template.runTransforms (/project/node_modules/@11ty/eleventy/src/Template.js:558:30)
[11ty]     at Template.renderPageEntry (/project/node_modules/@11ty/eleventy/src/Template.js:859:26)
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty]     at async /project/node_modules/@11ty/eleventy/src/Template.js:883:21
[11ty]     at async Promise.all (index 0)
```

(I've omitted part of my file path in the output above).

Have you come across this before?

Thanks again!

**Comment by kentaroi** [comment]
Thanks for filing the issue, @jamieomaguire!
I just fixed and published v1.2.5.
